Landing.PL/Areas/Dashboard/Controllers/SkillsController.cs
using AutoMapper;
using Landing.DAL.Data;
using Landing.DAL.Models;
using Landing.PL.Areas.Dashboard.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Landing.PL.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    [Authorize(Roles = "Admin , SuperAdmin")]


    public class SkillsController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public SkillsController(ApplicationDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            return View(mapper.Map<IEnumerable<SkillVM>>(context.Skills.ToList()));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SkillFormVM skillFormVM)
        {
            if (!ModelState.IsValid)
            {
                return View(skillFormVM);
            }

            var skill = mapper.Map<Skill>(skillFormVM);
            context.Add(skill);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int Id)
        {
            var skill = context.Skills.Find(Id);
            if (skill is null)
            {
                return NotFound();
            }

            return View(mapper.Map<SkillDetailsVM>(skill));
        }

        public IActionResult Edit(int Id)
        {
            var skill = context.Skills.Find(Id);
            if (skill is null)
            {
                return NotFound();
            }

            return View(mapper.Map<SkillFormVM>(skill));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SkillFormVM skillFormVM)
        {
            if (!ModelState.IsValid)
            {
                return View(skillFormVM);
            }

            var skill = context.Skills.Find(skillFormVM.Id);
            if (skill is null)
            {
                return NotFound();
            }

            mapper.Map(skillFormVM, skill);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            var skill = context.Skills.Find(id);
            if (skill is null)
            {
                return RedirectToAction(nameof(Index));
            }

            context.Skills.Remove(skill);
            context.SaveChanges();

            return Ok(new { message = "Delete  Skill Successfully" });
        }

    }
}

Landing.PL/Areas/Dashboard/Views/Skills/Create.cshtml
@model SkillFormVM

@section titleStart {
  Skills
}
@section titleSeceond {
    Create  Skill
}

@section Header {
Skills
}
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Skill</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->

        <form asp-controller="Skills" asp-action="Create">
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name"> Skill Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Enter Skill Name Required">
                    <span asp-validation-for="Name" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Value"> Skill Name</label>
                    <input asp-for="Value" class="form-control" placeholder="Enter Value Skill Required">
                    <span asp-validation-for="Value" class="text-danger"></span>

                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>

Landing.PL/Areas/Dashboard/Views/Skills/Details.cshtml
@model SkillDetailsVM
@section titleStart {
  Skills
}
@section titleSeceond {
    Details  Skill
}

@section Header {
  Details  Skill
}
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Skill Name is @Model.Name</h3>
        </div>
        <div class="card-body">
            <div class="SkillValue">
            <h3>Skill Value : </h3>
            <span class="d-flex justify-content-md-end">@Model.Value%</span>
            <div class="progress mb-3">
                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@Model.Value" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                    <span class="sr-only">@Model.Value%</span>
                </div>
            </div>
            </div>

            <p class="font-weight-bold text-sm">
                Status is : @(Model.IsDeleted ? "Deleted " : "Active")
            </p>
        </div>
        <div class="card-footer">
            <span class=" text-sm">CreatedAt : @Model.CreatedAt</span>
            <a class="btn btn-secondary btn-md  " asp-controller="Skills" asp-action="Index">Back</a>

        </div>
    </div>
</div>

Landing.PL/Areas/Dashboard/Views/Skills/Edit.cshtml
@model SkillFormVM
@section titleStart {
  Skills
}
@section titleSeceond {
    Edit  Skill
}

@section Header {
 Skills
}
<div class="col-md-12">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Edit Skill</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->

        <form asp-controller="Skills" asp-action="Edit">
            <div class="card-body">
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name">Skill Name</label>
                    <input asp-for="Name" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Value"> Skill Name</label>
                    <input asp-for="Value" class="form-control" >
                </div>

                <div class="form-group">
                    <label asp-for="IsDeleted">IsDeleted</label>
                    <input asp-for="IsDeleted" />
                    <span>@(Model.IsDeleted ? "Deleted" : "Active")</span>
                </div>


            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-info">Edit</button>
                <a class="btn btn-secondary btn-md " asp-controller="Skills" asp-action="Index">Cancel</a>

            </div>
        </form>
    </div>
</div>

Landing.PL/Areas/Dashboard/Views/Skills/Index.cshtml
@model IEnumerable<SkillVM>


@section style {
    <link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/3.1.2/css/buttons.dataTables.min.css" rel="stylesheet" />
}

@section titleStart {
    Skills
}
@section titleSeceond {
    All Skills
}

@section Header {
   Skills
}


<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">ALL Skills</h3>
        </div>
        <a class="btn btn-primary btn-md align-self-end mr-1 mt-1" asp-controller="Skills" asp-action="Create">Create</a>

        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Skill Name</th>
                        <th>Skill Value</th>
                        <th>IsDeleted</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Value</td>
                            <td>@item.IsDeleted</td>
                            <td>
                                <a class="btn btn-info btn-sm" asp-controller="Skills" asp-route-Id="@item.Id" asp-action="Details">Detailes</a>
                                <a class="btn btn-warning btn-sm" asp-controller="Skills" asp-route-Id="@item.Id" asp-action="Edit">Edit</a>
                                <a href="javascript:void(0)" data-Id="@item.Id" class="btn btn-danger btn-sm delete-btn">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->

    </div>
    <!-- /.card -->
</div>

@section script {
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" integrity="sha512-XMVd28F1oH/O71fzwBnV7HucLxVwtxf26XV8P4wPk26EDxuGZ91N8bsOttmnomcCD3CS5ZMRL50H0GgOHvegtg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/pdfmake.min.js" integrity="sha512-axXaF5grZBaYl7qiM6OMHgsgVXdSLxqq0w7F4CQxuFyrcPmn0JfnqsOtYHUun80g6mRRdvJDrTCyL8LQqBOt/Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/vfs_fonts.min.js" integrity="sha512-EFlschXPq/G5zunGPRSYqazR1CMKj0cQc8v6eMrQwybxgIbhsfoO5NAMQX3xFDQIbFlViv53o7Hy+yCWw6iZxA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.print.min.js"></script>


    <script>
        new DataTable('table', {
            layout: {
                topStart: {
                    buttons: [
                        'copy', 'excel', 'pdf'
                    ]
                }
            }
        });

        const DeleteButtons = document.querySelectorAll(".delete-btn");
        DeleteButtons.forEach(function (button) {

            button.addEventListener("click", async () => {

                const swalWithBootstrapButtons = Swal.mixin({
                    customClass: {
                        confirmButton: "btn btn-success",
                        cancelButton: "btn btn-danger"
                    },
                    buttonsStyling: false
                });
                swalWithBootstrapButtons.fire({

                    title: "Are you sure for delete skill ?",
                    text: "you are have for delete skill finally!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel!",
                    reverseButtons: true
                }).then(async (result) => {
                    if (result.isConfirmed) {
                        const id = button.dataset.id;

                        const response = await fetch(`/Dashboard/Skills/DeleteConfirm/${id}`, {
                            method: 'POST',
                            headers: {
                                "Content-Type": "application/json"
                            }
                        });
                        const data = await response.json();
                        console.log(data);

                        if (response.ok) {
                            $(button).closest("tr").remove();
                        }

                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 3000,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });
                        Toast.fire({
                            icon: "success",
                            title: "Skill Deleted is successfully"
                        });
                    } else if (
                        /* Read more about handling dismissals below */
                        result.dismiss === Swal.DismissReason.cancel
                    ) {
                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 3000,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });
                        Toast.fire({
                            icon: "error",
                            title: "delete skill is cancelled "
                        });
                    }
                });


            })

        })


    </script>
}