Landing.PL/Areas/Dashboard/Controllers/ServicesController.cs
using AutoMapper;
using Landing.DAL.Data;
using Landing.DAL.Models;
using Landing.PL.Areas.Dashboard.ViewModel;
using Landing.PL.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Landing.PL.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    [Authorize(Roles ="Admin , SuperAdmin")]
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public ServicesController(ApplicationDbContext context , IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {        
            return View(mapper.Map<IEnumerable<ServiceVM>>(context.Services.ToList()));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ServiceFormVM serviceFormVM)
        {
            if (!ModelState.IsValid) { 
                return View(serviceFormVM);
            }
          serviceFormVM.ImageName = FileSettings.UploadFile(serviceFormVM.Image, "images");
            
            var service = mapper.Map<Service>(serviceFormVM);
            context.Add(service);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int Id)
        {
            var service = context.Services.Find(Id);
            if(service is null)
            {
                return NotFound();
            }

            return View(mapper.Map<ServiceDetailsVM>(service));
        }

        public IActionResult Edit(int Id)
        {
            var service = context.Services.Find(Id);
            if (service is null)
            {
                return NotFound();
            }

            return View(mapper.Map<ServiceFormVM>(service));
        }
     [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(ServiceFormVM serviceFormVM)
        {

            var service = context.Services.Find(serviceFormVM.Id);
            if (service is null)
            {
                return NotFound();
            }
            if(serviceFormVM.Image is null)
            {
                ModelState.Remove("Image");
            }
            else
            {
               FileSettings.DeleteFile(service.ImageName, "images");
               serviceFormVM.ImageName = FileSettings.UploadFile(serviceFormVM.Image, "images");

            }

            if (!ModelState.IsValid) {
                return View(serviceFormVM);
            }
           

            mapper.Map(serviceFormVM, service);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            var service = context.Services.Find(id);
            if (service is null)
            {
                return RedirectToAction(nameof(Index));
            }
            FileSettings.DeleteFile(service.ImageName , "images");
            context.Services.Remove(service);
            context.SaveChanges();

            return Ok(new {message="Delete Service Successfully"});
        }


        }


    }

Landing.PL/Controllers/ServicesController.cs
using AutoMapper;
using Landing.DAL.Data;
using Landing.DAL.Models;
using Landing.PL.Helper;
using Landing.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Landing.PL.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ILogger<ServicesController> _logger;
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;
        private readonly Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> userManager;

        public ServicesController(ILogger<ServicesController> logger, ApplicationDbContext context, IMapper mapper, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            this.context = context;
            this.mapper = mapper;
            this.userManager = userManager;
        }
        public IActionResult Index()
        {
            var ser = context.Services.Where(s=>!s.IsDeleted).ToList();
            var services = mapper.Map<IEnumerable<ServiceDisplayVM>>(ser);
            var prices = mapper.Map<IEnumerable<PriceDisplayVM>>(context.Prices.ToList());
            ViewData[nameof(services)] = services;
            ViewData[nameof(prices)] = prices;
            return View();
        }

        public IActionResult Details(int Id)
        {
            var service = context.Services.Find(Id);
            if (service == null)
            {
                return NotFound();
            }
            var serviceDisplay = mapper.Map<ServiceDisplayVM>(service);
            var services = ViewData["services"] as IEnumerable<ServiceDisplayVM>;

            ViewData[nameof(serviceDisplay)] = serviceDisplay;
            ViewData[nameof(services)] = services;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpgradePlan(int priceId)
        {
            var user = await userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound("User not found."); 
            }

            var selectedPrice = await context.Prices.FirstOrDefaultAsync(p => p.Id == priceId);
            if (selectedPrice == null)
            {
                return BadRequest("Selected plan does not exist."); 
            }

            user.PriceId = selectedPrice.Id;
            user.Price = selectedPrice;

            var result = await userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
               
                var email = new Email
                {
                    Recivers = user.Email,
                    Subject = "Plan Upgrade Confirmation",
                    Body = $"Hello {user.UserName},\n\n" +
                           $"Your account has been successfully upgraded to the {selectedPrice.Name}, {selectedPrice.FinalPrice}$ plan.\n\n" +
                           $"For Payment Purches Contact us by Email or PhoneNumber" +
                           $"Thank you for upgrading!\n\nBest Regards,\nYour Company Team"
                };
                EmailSettings.SendEmail(email);

                return Ok();
            }

            return BadRequest("Failed to upgrade plan."); 
        }




    }
}

Landing.PL/Areas/Dashboard/Views/Services/Create.cshtml
@model ServiceFormVM



@section titleStart {
    Services
}
@section titleSeceond {
    Create Service
}
@section Header{
  Services
}
<div class="col-md-12">
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Create Service</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
   
    <form asp-controller="Services" asp-action="Create" enctype="multipart/form-data"> 
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Name">Service Name</label>
                <input asp-for="Name" class="form-control" placeholder="Enter Service Name Required">
                <span asp-validation-for="Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                    <input asp-for="Description" class="form-control textarea" placeholder="Enter Service Description Required">
                    <span asp-validation-for="Description" class="text-danger"></span>

            </div>
                <div class="form-group">
                    <label asp-for="Image">Upload Image</label>
                    <input asp-for="Image" class="imageInput" >
                    <span asp-validation-for="Image" class="text-danger"></span>

                </div>
                <div class="form-group">
                   <img src="#" id="imagePreview" width="50" style="display:none" alt="this is image service" />
                </div>

         
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>
</div>
</div>

@section script{
    <script src="https://cdn.tiny.cloud/1/6flbm5mj6i3yf3fgi2p9ij1bsfnjsu15kmtzer7qs3vfeq43/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: '.textarea',
            plugins: [
                // Core editing features
                'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'image', 'link', 'lists', 'media', 'searchreplace', 'table', 'visualblocks', 'wordcount',
                // Your account includes a free trial of TinyMCE premium features
                // Try the most popular premium features until Oct 27, 2024:
                'checklist', 'mediaembed', 'casechange', 'export', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'editimage', 'advtemplate', 'ai', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown',
            ],
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        });
        document.querySelector(".imageInput").addEventListener("change", (event) => {
            const file = event.target.files[0];
            const imagePreview = document.querySelector("#imagePreview");

            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    imagePreview.src = e.target.result;
                    imagePreview.style.display = "block";
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
}

Landing.PL/Areas/Dashboard/Views/Services/Details.cshtml
@model ServiceDetailsVM

@section titleStart {
    Services
}
@section titleSeceond {
    Details Service
}

@section Header {
    Details Service
}
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Service Name is @Model.Name</h3>
        </div>
        <div class="card-body">
            <div class="post">
                <img class="img-lg img-rounded" src="~/Files/images/@Model.ImageName" alt="this is service image :@Model.Name">

                <p class="font-weight-bolder " style="color:black">
                    Description :@Html.Raw(@Model.Description)
                </p>
                <p class="font-weight-bold text-sm">
                    Status is : @(Model.IsDeleted ? "Deleted " : "Active")
                </p>
            </div>
        </div>
        <div class="card-footer">
            <span class=" text-sm">CreatedAt : @Model.CreatedAt</span>
            <a class="btn btn-secondary btn-md  " asp-controller="Services" asp-action="Index">Back</a>

        </div>
        </div>
        </div>

Landing.PL/Areas/Dashboard/Views/Services/Edit.cshtml
@model ServiceFormVM

@section titleStart {
    Services
}
@section titleSeceond {
    Edit Service
}

@section Header {
  Services
}
<div class="col-md-12">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Edit Service</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->

        <form asp-controller="Services" asp-action="Edit" enctype="multipart/form-data">
            <div class="card-body">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ImageName"/>
                <div class="form-group">
                    <label asp-for="Name">Service Name</label>
                    <input asp-for="Name" class="form-control" >
                </div>
                <div class="form-group">
                    <label asp-for="Description">Description</label>
                    <input asp-for="Description" class="form-control textarea" >
                </div>
                <div class="form-group">
                    <label asp-for="IsDeleted">IsDeleted</label>
                    <input asp-for="IsDeleted" />
                    <span>@(Model.IsDeleted?"Deleted" : "Active")</span>
                </div>
                <div class="form-group">
                    <label asp-for="Image">Upload Image</label>
                    <input asp-for="Image" class="imageInput">
                </div>
                <div class="form-group">
                    <img src="#" id="imagePreview" width="50" style="display:none" alt="this is image service" />
                </div>

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-info">Edit</button>
                <a class="btn btn-secondary btn-md " asp-controller="Services" asp-action="Index">Cancel</a>

            </div>
        </form>
    </div>
</div>
@section script {
    <script src="https://cdn.tiny.cloud/1/6flbm5mj6i3yf3fgi2p9ij1bsfnjsu15kmtzer7qs3vfeq43/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: '.textarea',
            plugins: [
                // Core editing features
                'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'image', 'link', 'lists', 'media', 'searchreplace', 'table', 'visualblocks', 'wordcount',
                // Your account includes a free trial of TinyMCE premium features
                // Try the most popular premium features until Oct 27, 2024:
                'checklist', 'mediaembed', 'casechange', 'export', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'editimage', 'advtemplate', 'ai', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown',
            ],
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        });
        document.querySelector(".imageInput").addEventListener("change", (event) => {
            const file = event.target.files[0];
            const imagePreview = document.querySelector("#imagePreview");

            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    imagePreview.src = e.target.result;
                    imagePreview.style.display = "block";
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
}

Landing.PL/Areas/Dashboard/Views/Services/Index.cshtml
@model IEnumerable<ServiceVM>



@section style {
    <link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/3.1.2/css/buttons.dataTables.min.css" rel="stylesheet" />
}
@section titleStart{
    Services
}
@section titleSeceond {
    All Services
}

@section Header{
   Services
}



<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">ALL Services</h3>
        </div>
        <a class="btn btn-primary btn-md align-self-end mr-1 mt-1" asp-controller="Services" asp-action="Create">Create</a>

        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>IsDeleted</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.IsDeleted</td>
                            <td>
                                <a class="btn btn-info btn-sm" asp-controller="Services" asp-route-Id="@item.Id" asp-action="Details">Detailes</a>
                                <a class="btn btn-warning btn-sm" asp-controller="Services" asp-route-Id="@item.Id" asp-action="Edit">Edit</a>
                                <a href="javascript:void(0)" data-Id ="@item.Id" class="btn btn-danger btn-sm delete-btn">Delete</a>
                            </td>
                        </tr>  
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
      
    </div>
    <!-- /.card -->
</div>

@section script{
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" integrity="sha512-XMVd28F1oH/O71fzwBnV7HucLxVwtxf26XV8P4wPk26EDxuGZ91N8bsOttmnomcCD3CS5ZMRL50H0GgOHvegtg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/pdfmake.min.js" integrity="sha512-axXaF5grZBaYl7qiM6OMHgsgVXdSLxqq0w7F4CQxuFyrcPmn0JfnqsOtYHUun80g6mRRdvJDrTCyL8LQqBOt/Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/vfs_fonts.min.js" integrity="sha512-EFlschXPq/G5zunGPRSYqazR1CMKj0cQc8v6eMrQwybxgIbhsfoO5NAMQX3xFDQIbFlViv53o7Hy+yCWw6iZxA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.print.min.js"></script>


    <script>
        new DataTable('table', {
            layout: {
                topStart: {
                    buttons: [
                        'copy', 'excel', 'pdf'
                    ]
                }
            }
        });

        const DeleteButtons = document.querySelectorAll(".delete-btn");
        DeleteButtons.forEach(function (button) {

            button.addEventListener("click", async () => {

                const swalWithBootstrapButtons = Swal.mixin({
                    customClass: {
                        confirmButton: "btn btn-success",
                        cancelButton: "btn btn-danger"
                    },
                    buttonsStyling: false
                });
                swalWithBootstrapButtons.fire({

                    title: "Are you sure for delete service ?",
                    text: "you are have for delete service finally!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel!",
                    reverseButtons: true
                }).then(async (result) => {
                    if (result.isConfirmed) {
                        const id = button.dataset.id;

                        const response = await fetch(`/Dashboard/Services/DeleteConfirm/${id}`, {
                            method: 'POST',
                            headers: {
                                "Content-Type": "application/json"
                            }
                        });
                        const data = await response.json();
                        console.log(data);

                        if (response.ok) {
                            $(button).closest("tr").remove();
                        }

                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 3000,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });
                        Toast.fire({
                            icon: "success",
                            title: "Service Deleted is successfully"
                        });
                    } else if (
                        /* Read more about handling dismissals below */
                        result.dismiss === Swal.DismissReason.cancel
                    ) { 
                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 3000,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });
                    Toast.fire({
                        icon: "error",
                        title: "delete service is cancelled "
                    });
                }
                });


            })

        })


    </script>
}