Landing.PL/Areas/Dashboard/Controllers/PortfoliosController.cs
using AutoMapper;
using Landing.DAL.Data;
using Landing.DAL.Models;
using Landing.PL.Areas.Dashboard.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Landing.PL.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    [Authorize(Roles = "Admin , SuperAdmin")]


    public class PortfoliosController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public PortfoliosController(ApplicationDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            return View(mapper.Map<IEnumerable<PortfolioVM>>(context.Portfolios.ToList()));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PortfolioFormVM portfolioFormVM)
        {
            if (!ModelState.IsValid)
            {
                return View(portfolioFormVM);
            }

            var portfolio = mapper.Map<Portfolio>(portfolioFormVM);
            context.Add(portfolio);
            context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int Id)
        {
            var portfolio = context.Portfolios.Find(Id);
            if (portfolio is null)
            {
                return NotFound();
            }

            return View(mapper.Map<PortfolioDetailsVM>(portfolio));
        }

        public IActionResult Edit(int Id)
        {
            var portfolio = context.Portfolios.Find(Id);
            if (portfolio is null)
            {
                return NotFound();
            }

            return View(mapper.Map<PortfolioFormVM>(portfolio));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PortfolioFormVM portfolioFormVM)
        {
            if (!ModelState.IsValid)
            {
                return View(portfolioFormVM);
            }

            var portfolio = context.Portfolios.Find(portfolioFormVM.Id);
            if (portfolio is null)
            {
                return NotFound();
            }
         
            mapper.Map(portfolioFormVM, portfolio);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            var portfolio = context.Portfolios.Find(id);
            if (portfolio is null)
            {
                return RedirectToAction(nameof(Index));
            }

            context.Portfolios.Remove(portfolio);
            context.SaveChanges();

            return Ok(new { message = "Delete  portfolio Successfully" });
        }
    }
}

Landing.PL/Controllers/PortfoliosController.cs
using AutoMapper;
using Landing.DAL.Data;
using Landing.PL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Landing.PL.Controllers
{
    public class PortfoliosController : Controller
    {
        private readonly ILogger<PortfoliosController> _logger;
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public PortfoliosController(ILogger<PortfoliosController> logger, ApplicationDbContext context, IMapper mapper)
        {
            _logger = logger;
            this.context = context;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var por = context.Portfolios.Where(s => !s.IsDeleted).ToList();
            var portfolios = mapper.Map<IEnumerable<PortfolioDisplayVM>>(por);
            var Items = mapper.Map<IEnumerable<ItemDisplayVM>>(context.Items.ToList());
            ViewData[nameof(portfolios)] = portfolios;
            ViewData[nameof(Items)] = Items;
            return View();
        }
        public IActionResult Details(int Id)
        {
            var item = context.Items.Include(i => i.Portfolio).FirstOrDefault(p=>p.Id==Id);
            if (item == null)
            {
                return NotFound();
            }
            var itemDetails = mapper.Map<ItemDisplayVM>(item);

            ViewData[nameof(itemDetails)] = itemDetails;

            return View();
        }
    }
}

Landing.PL/Areas/Dashboard/Views/Portfolios/Create.cshtml
@model PortfolioFormVM

@section titleStart {
  Portfolios
}
@section titleSeceond {
    Create  Portfolio
}

@section Header {
  Portfolios
}
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Portfolio</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->

        <form asp-controller="Portfolios" asp-action="Create">
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name"> Portfolio Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Enter Portfolios Name Required">
                    <span asp-validation-for="Name" class="text-danger"></span>

                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>

Landing.PL/Areas/Dashboard/Views/Portfolios/Details.cshtml
@model PortfolioDetailsVM
@section titleStart {
  Portfolios
}
@section titleSeceond {
    Details  Portfolio
}

@section Header {
    Details Portfolio
}
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Portfolio Name is @Model.Name</h3>
        </div>
        <div class="card-body">
         
            <p class="font-weight-bold text-sm">
                Status is : @(Model.IsDeleted ? "Deleted " : "Active")
            </p>
        </div>
        <div class="card-footer">
            <span class=" text-sm">CreatedAt : @Model.CreatedAt</span>
            <a class="btn btn-secondary btn-md  " asp-controller="Portfolios" asp-action="Index">Back</a>

        </div>
    </div>
</div>

Landing.PL/Areas/Dashboard/Views/Portfolios/Edit.cshtml
@model PortfolioFormVM
@section titleStart {
  Portfolios
}
@section titleSeceond {
    Edit  Portfolio
}

@section Header {
 Portfolios
}
<div class="col-md-12">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Edit Portfolio</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->

        <form asp-controller="Portfolios" asp-action="Edit">
            <div class="card-body">
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name">Portfolio Name</label>
                    <input asp-for="Name" class="form-control">
                </div>
             
                <div class="form-group">
                    <label asp-for="IsDeleted">IsDeleted</label>
                    <input asp-for="IsDeleted" />
                    <span>@(Model.IsDeleted ? "Deleted" : "Active")</span>
                </div>
               

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-info">Edit</button>
                <a class="btn btn-secondary btn-md " asp-controller="Portfolios" asp-action="Index">Cancel</a>

            </div>
        </form>
    </div>
</div>

Landing.PL/Areas/Dashboard/Views/Portfolios/Index.cshtml
@model IEnumerable<PortfolioVM>


@section style {
    <link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/3.1.2/css/buttons.dataTables.min.css" rel="stylesheet" />
}

@section titleStart {
  Portfolios
}
@section titleSeceond {
    All Portfolios
}

@section Header {
   Portfolios
}


<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">ALL Portfolios</h3>
        </div>
        <a class="btn btn-primary btn-md align-self-end mr-1 mt-1" asp-controller="Portfolios" asp-action="Create">Create</a>

        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Portfolio Name</th>
                        <th>IsDeleted</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.IsDeleted</td>
                            <td>
                                <a class="btn btn-info btn-sm" asp-controller="Portfolios" asp-route-Id="@item.Id" asp-action="Details">Detailes</a>
                                <a class="btn btn-warning btn-sm" asp-controller="Portfolios" asp-route-Id="@item.Id" asp-action="Edit">Edit</a>
                                <a href="javascript:void(0)" data-Id="@item.Id" class="btn btn-danger btn-sm delete-btn">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->

    </div>
    <!-- /.card -->
</div>

@section script {
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" integrity="sha512-XMVd28F1oH/O71fzwBnV7HucLxVwtxf26XV8P4wPk26EDxuGZ91N8bsOttmnomcCD3CS5ZMRL50H0GgOHvegtg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/pdfmake.min.js" integrity="sha512-axXaF5grZBaYl7qiM6OMHgsgVXdSLxqq0w7F4CQxuFyrcPmn0JfnqsOtYHUun80g6mRRdvJDrTCyL8LQqBOt/Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/vfs_fonts.min.js" integrity="sha512-EFlschXPq/G5zunGPRSYqazR1CMKj0cQc8v6eMrQwybxgIbhsfoO5NAMQX3xFDQIbFlViv53o7Hy+yCWw6iZxA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.print.min.js"></script>


    <script>
        new DataTable('table', {
            layout: {
                topStart: {
                    buttons: [
                        'copy', 'excel', 'pdf'
                    ]
                }
            }
        });

        const DeleteButtons = document.querySelectorAll(".delete-btn");
        DeleteButtons.forEach(function (button) {

            button.addEventListener("click", async () => {

                const swalWithBootstrapButtons = Swal.mixin({
                    customClass: {
                        confirmButton: "btn btn-success",
                        cancelButton: "btn btn-danger"
                    },
                    buttonsStyling: false
                });
                swalWithBootstrapButtons.fire({

                    title: "Are you sure for delete portfolio ?",
                    text: "you are have for delete portfolio finally!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel!",
                    reverseButtons: true
                }).then(async (result) => {
                    if (result.isConfirmed) {
                        const id = button.dataset.id;

                        const response = await fetch(`/Dashboard/Portfolios/DeleteConfirm/${id}`, {
                            method: 'POST',
                            headers: {
                                "Content-Type": "application/json"
                            }
                        });
                        const data = await response.json();
                        console.log(data);

                        if (response.ok) {
                            $(button).closest("tr").remove();
                        }

                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 3000,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });
                        Toast.fire({
                            icon: "success",
                            title: "Portfolio Deleted is successfully"
                        });
                    } else if (
                        /* Read more about handling dismissals below */
                        result.dismiss === Swal.DismissReason.cancel
                    ) {
                        const Toast = Swal.mixin({
                            toast: true,
                            position: "top-end",
                            showConfirmButton: false,
                            timer: 3000,
                            timerProgressBar: true,
                            didOpen: (toast) => {
                                toast.onmouseenter = Swal.stopTimer;
                                toast.onmouseleave = Swal.resumeTimer;
                            }
                        });
                        Toast.fire({
                            icon: "error",
                            title: "delete portfolio is cancelled "
                        });
                    }
                });


            })

        })


    </script>
}